### ISSUE TITLE
documentation?

### ISSUE THREAD

**Issue by myusuf3** [zachcp/quickD3map#1]
There is actually zero way of telling the user on how to use this. Please fix :)

**Comment by zachcp** [comment]
hi @myusuf3,

this is currently an experimental repo. I hope to make it into a simple utility for creating wuick point maps but right now there is just the skeleton. 

I've updated the README to indicate this is still experimental but will try to get up some simple documentation for the curious.

thanks fro your interest
zach cp

**Comment by zachcp** [comment]
@myusuf3 I pushed a small update with a basic example. If you have dataframes with global data it will work.

**Comment by myusuf3** [comment]
+1
