### ISSUE TITLE
No module named MultiColumnMap

### ISSUE THREAD

**Issue by ghost** [zachcp/quickD3map#13]
hackerotaku@BrightLight:~/Downloads/quickD3map$ python
Python 2.7.6 |Anaconda 1.9.1 (64-bit)| (default, Jan 17 2014, 10:13:17)
[GCC 4.1.2 20080704 (Red Hat 4.1.2-54)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > from quickD3map import PointMap
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "quickD3map/**init**.py", line 11, in <module>
> > >     from .MultiColumnMap import MultiColumnMap
> > > ImportError: No module named MultiColumnMap
> > > import quickD3map
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "quickD3map/**init**.py", line 11, in <module>
> > >     from .MultiColumnMap import MultiColumnMap
> > > ImportError: No module named MultiColumnMap

**Comment by zachcp** [comment]
@alienone  thanks for pointing this out. I fixed the import error and pushed a minor release. It should work now.
